modulelist=com.p6spy.engine.spy.P6SpyFactory
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.roastive.api.config.P6SpySqlFormatter
databaseDialectDateFormat=yyyy-MM-dd HH:mm:ss
excludecategories=info,debug,result,batch
excludefilter=.*app_menu.*
executionThreshold=0
logParameterValues=true